export const REQUEST_LOAD_USER = 'REQUEST_LOAD_USER';
export const LOADING_USER = 'LOADING_USER';
export const SUCCESS_LOAD_USER = 'SUCCESS_LOAD_USER';
export const ERROR_LOAD_USER = 'ERROR_LOAD_USER';